server:
  port: 8001
temp:
  chunk_temp_file_path: /Users/krasus1966/temp/testChunk/
spring:
  messages:
    basename: i18n.constants
    encoding: UTF-8
  data:
    mongodb:
      uri: mongodb://admin:196610121@localhost:27017/news
#      host: localhost
#      port: 27017
#      authentication-database: news
#      username: admin
#      password: 196610121
#      database: news
      gridfs:
        bucket: fs
  servlet:
    multipart:
      max-file-size: 10000MB
